StarlightProperties/Models/ErrorViewModel.cs
namespace StarlightProperties.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StarlightProperties/Models/House.cs
using System.ComponentModel.DataAnnotations;

namespace StarlightProperties.Models
{
    public class House
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(150)]
        [Display(Name = "Property Name")]
        [DataType(DataType.Text)]
        public string? PropertyName { get; set; }

        [Required]
        [MaxLength(150)]
        [Display(Name = "Owner Name")]
        [DataType(DataType.Text)]
        public string? OwnerName { get; set; }

        [Required]
        [Display(Name = "Owner Contact Number")]
        [DataType(DataType.PhoneNumber)]
        public int OwnerContact { get; set; }

        [Required]
        [Display(Name = "Property Value")]
        [DataType(DataType.Currency)]
        public int PropertyValue { get; set; }

        [Required]
        [Display(Name = "Property Size")]
        [DataType(DataType.Text)]
        public int PropertySize { get; set; }

        [Required]
        [Display(Name = "Number of Rooms")]
        [DataType(DataType.Text)]
        public int NumberRoom { get; set; }

        [Required]
        [MaxLength(150)]
        [Display(Name = "Location")]
        [DataType(DataType.Text)]
        public string? Location { get; set; }

    }
}

StarlightProperties/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StarlightProperties.Models;
using System.Diagnostics;

namespace StarlightProperties.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StarlightProperties/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StarlightProperties.Data;
using StarlightProperties.Models;

namespace StarlightProperties.Controllers
{
    public class HousesController : Controller
    {
        private readonly HomeDbContext _context;

        public HousesController(HomeDbContext context)
        {
            _context = context;
        }

        [Authorize]
        [HttpGet]

        public async Task<IActionResult> Index(string OwnerSearch)
        {
            ViewData["GetOwnerName"] = OwnerSearch;

            var ownerquery = from x in _context.House select x;
            if (!String.IsNullOrEmpty(OwnerSearch))
            {
                ownerquery = ownerquery.Where(x => x.OwnerName.Contains(OwnerSearch) || x.PropertyName.Contains(OwnerSearch));
            }
            return View(await ownerquery.AsNoTracking().ToListAsync());
        }

        [Authorize]
        // GET: Houses
        public async Task<IActionResult> Index()
        {
            return View(await _context.House.ToListAsync());
        }

        // GET: Houses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var house = await _context.House
                .FirstOrDefaultAsync(m => m.Id == id);
            if (house == null)
            {
                return NotFound();
            }

            return View(house);
        }

        // GET: Houses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Houses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PropertyName,OwnerName,OwnerContact,PropertyValue,PropertySize,NumberRoom,Location")] House house)
        {
            if (ModelState.IsValid)
            {
                _context.Add(house);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(house);
        }

        // GET: Houses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var house = await _context.House.FindAsync(id);
            if (house == null)
            {
                return NotFound();
            }
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PropertyName,OwnerName,OwnerContact,PropertyValue,PropertySize,NumberRoom,Location")] House house)
        {
            if (id != house.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(house);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HouseExists(house.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(house);
        }

        // GET: Houses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var house = await _context.House
                .FirstOrDefaultAsync(m => m.Id == id);
            if (house == null)
            {
                return NotFound();
            }

            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var house = await _context.House.FindAsync(id);
            if (house != null)
            {
                _context.House.Remove(house);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HouseExists(int id)
        {
            return _context.House.Any(e => e.Id == id);
        }
    }
}

StarlightProperties/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Us";
}

<html>
<head>
    <style>
        * {
            box-sizing: border-box;
            
        }

        .imgbox {
            display: grid;
            height: 100%;
        }

        .center-fit {
            max-width: 100%;
            max-height: 100%;
            
            margin: 0px;
            
            
        }
    </style>
</head>
<body>
    <div class="imgbox">
        <img class="center-fit" src="https://cdn.discordapp.com/attachments/1133039917094682644/1197184958536634419/ABOUT_US_1.png?ex=65ba5860&is=65a7e360&hm=997f017c4761048579876cf7a565212d7cffb909e158de307af54ecfd3733cb7&">
    </div>
    </br>
    </br>
	
		
	
	

				<div class="grid1">
					
					<h1>Where Your Dream Home Awaits!</h1>
                    </br>
				</div>
				<div class="clear"></div>
				<div class="about-des">

                    <p>
                        Welcome to Starlight Properties, your dedicated partner in the pursuit of the perfect home. At Starlight Properties, we stand out in the real estate industry with our commitment to excellence, transparency, and personalized service. Our seasoned estate agents specialize in connecting aspiring homeowners with a diverse portfolio of available estates, ensuring a seamless and enjoyable journey towards finding the property that aligns with your unique vision and lifestyle.
                    </br> </br>
                        What sets us apart is our genuine passion for real estate and our mission to simplify the property search process for our clients. We believe in fostering lasting relationships by understanding your unique needs and delivering tailored solutions. Whether you're a first-time homebuyer, a seasoned investor, or looking to upgrade, our experienced team is here to guide you every step of the way. With Starlight Properties, your dream home is not just a possibility; it's a certainty.
                    </br> </br>
                        Explore our website to discover the latest listings, expert advice, and resources that will enhance your real estate journey. Thank you for choosing Starlight Properties - Where Your Dream Home Awaits!
                    </p>
                    </br>
                    </br>
                    <h1>ORGANIZATIONAL CHART</h1>
					
				</div>

                <div class="imgbox">
                    <img class="center-fit" src="https://cdn.discordapp.com/attachments/1133039917094682644/1197194048730042468/Organizational-Chart-with-Images.png?ex=65ba60d8&is=65a7ebd8&hm=d1dd61ace382130cc9199e91b2756271d0e1621c78fb30be71b9e7eff23a29ab&">
                </div>
</body>
</html>

   

        

    

StarlightProperties/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<body>
<div>
    <br />
    <br />

    <table>
        <tr>
            <td><h1 class="text-center"> WELCOME TO STARLIGHT PROPERTIES</h1>
                <p class="text-center"> Our company will keep track and supply estate agents with available property for organization or customer who are looking to do business</p></td>
            <td> <img src="https://cdn.discordapp.com/attachments/1133039917094682644/1194559496568193084/pngwing.com.png?ex=65b0cb39&is=659e5639&hm=476cf00e3c5833cffbec64b7aa67e49958d77ec5dfbb1ef5020275fa6b9d51b1&"</td>
        </tr>
             
    </table>

    <br />
    <br />
    <br />
    <br />

    
    <h1 class="text-center">LOCATIONS</h1>
    <p class="text-center">We are an organization from Malaysia so our properties listed are only available in Malaysia</p>
    
    <br />

    <table>
        <tr>
            <td> <img src="https://www.google.com/maps/d/u/0/thumbnail?mid=1AchMAZrtBf74YD1Kv2vfyxLNOng&hl=en" width="450"</td>
            <td> <img src="https://www.google.com/maps/d/u/0/thumbnail?mid=116xQeNuNRv9ADRD8ICcooyHyWac&hl=en_US" width="450"</td>
            <td> <img src="https://www.google.com/maps/d/u/0/thumbnail?mid=18AUfTG3r-kvkuQRammjivvjtidg&hl=en" width="450"</td>
        </tr>
    </table>
   

    <br />
    <br />
    <br />
    <br />

    <table>
        <tr>

            <td> <img src="https://i.pinimg.com/originals/cd/33/3a/cd333aab10687b07b3bbb7eadb9b457c.png" width="600"</td>
            <td>
                <h1 class="text-center"> CHOOSE US</h1>
                <p class="text-center"> Our company will keep track and supply estate agents with available property for organization or customer who are looking to do business</p>
            </td>
            
        </tr>

    </table>
</div>
</body>

StarlightProperties/Views/Houses/Create.cshtml
@model StarlightProperties.Models.House

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>House</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PropertyName" class="control-label"></label>
                <input asp-for="PropertyName" class="form-control" />
                <span asp-validation-for="PropertyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerName" class="control-label"></label>
                <input asp-for="OwnerName" class="form-control" />
                <span asp-validation-for="OwnerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerContact" class="control-label"></label>
                <input asp-for="OwnerContact" class="form-control" />
                <span asp-validation-for="OwnerContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertyValue" class="control-label"></label>
                <input asp-for="PropertyValue" class="form-control" />
                <span asp-validation-for="PropertyValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertySize" class="control-label"></label>
                <input asp-for="PropertySize" class="form-control" />
                <span asp-validation-for="PropertySize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberRoom" class="control-label"></label>
                <input asp-for="NumberRoom" class="form-control" />
                <span asp-validation-for="NumberRoom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StarlightProperties/Views/Houses/Delete.cshtml
@model StarlightProperties.Models.House

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>House</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerContact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerContact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertySize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertySize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberRoom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StarlightProperties/Views/Houses/Details.cshtml
@model StarlightProperties.Models.House

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>House</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerContact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerContact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertySize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertySize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberRoom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StarlightProperties/Views/Houses/Edit.cshtml
@model StarlightProperties.Models.House

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>House</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PropertyName" class="control-label"></label>
                <input asp-for="PropertyName" class="form-control" />
                <span asp-validation-for="PropertyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerName" class="control-label"></label>
                <input asp-for="OwnerName" class="form-control" />
                <span asp-validation-for="OwnerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerContact" class="control-label"></label>
                <input asp-for="OwnerContact" class="form-control" />
                <span asp-validation-for="OwnerContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertyValue" class="control-label"></label>
                <input asp-for="PropertyValue" class="form-control" />
                <span asp-validation-for="PropertyValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertySize" class="control-label"></label>
                <input asp-for="PropertySize" class="form-control" />
                <span asp-validation-for="PropertySize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberRoom" class="control-label"></label>
                <input asp-for="NumberRoom" class="form-control" />
                <span asp-validation-for="NumberRoom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StarlightProperties/Views/Houses/Index.cshtml
@model IEnumerable<StarlightProperties.Models.House>

@{
    ViewData["Title"] = "Properties";
}

<h1>Properties</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form method="get" asp-action="Index">
    <p>
        <input type="search" placeholder="Enter Owner Name or Property Name" value="@ViewData[" GetOwnerName"]" name= "OwnerSearch" style="width:500px;" />
        <input type="submit" value="Search" class="btn btn-primary" />
        <a asp-action="Index">Get All Properties</a>
    </p>


</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PropertyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerContact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertySize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberRoom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerContact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyValue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertySize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberRoom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

StarlightProperties/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Starlight Properties</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StarlightProperties.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#131e3a">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://cdn.discordapp.com/attachments/1133039917094682644/1194552987004186634/STARLIGht_prop.png?ex=65b0c529&is=659e5029&hm=104aa361863a92db5231de024ba9b3e87e0d95157e1ef20abd4c1f90d0425a94&" height="50" width="50" /> STARLIGHTPROPERTIES
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Houses" asp-action="Index">Properties</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color:#131e3a" class="border-top footer text-white">
        <div class="container">
            &copy; 2024 - STARLIGHTPROPERTIES - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>